api:
  dashboard: true
  insecure: false

providers:
  docker:
    exposedByDefault: false
    network: pbx-net
  file:
    directory: /etc/traefik/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: ssl@telonova.at
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}
